////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Interface: typing-indicator
// Integrations: webchat
// Version: 0.0.3
// File: typing_indicator/index.ts
// Hash: df88eb4c7e4c6afb18fe66a9468916cb9039eef2983befbc0da22ea9970304dd
// Updated at: 2025-12-16T19:34:19.049Z
////////////////////////////////////////////////////////

import { Interface_Actions_TypingIndicator } from "./actions";

export * from "./actions";

export type Interface_All_TypingIndicator = {
  actions: Interface_Actions_TypingIndicator;
};

export const Interface_All_TypingIndicator = {
  actions: Interface_Actions_TypingIndicator,
};
