////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Generated at: 2026-04-02T22:26:48.137Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/actions" {
  export interface CallableAction<I, O> {
    (input: I): Promise<O>;
    asTool(): import("@botpress/runtime").Autonomous.Tool;
  }

  export type BotActionDefinitions = {
    tablesRecomputeRows: {
      input: any;
      output: any;
    };
  };

  export type BotActions = {
    [K in keyof BotActionDefinitions]: CallableAction<
      BotActionDefinitions[K]["input"],
      BotActionDefinitions[K]["output"]
    >;
  };
}
