////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Generated at: 2026-04-02T22:26:48.137Z
////////////////////////////////////////////////////////

type Integrations = import("@botpress/runtime/_types/integrations").Integrations;
type ConversationTags = import("@botpress/runtime/_types/tags").ConversationTags;
type MessageTags = import("@botpress/runtime/_types/tags").MessageTags;

declare module "@botpress/runtime/_types/conversations" {
  export type ConversationDefinitions = {
    // No conversations defined yet
  };

  /**
   * Events that can be routed to conversations (events with conversationId property).
   * Keyed by channel, containing a tuple of event names that have conversationId.
   */
  export type ConversationRoutableEvents = {
    // No routable events found
  };
}
