////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Generated at: 2026-04-02T22:26:48.138Z
////////////////////////////////////////////////////////

type Integrations = import("@botpress/runtime/_types/integrations").Integrations;

declare module "@botpress/runtime/_types/events" {
  /**
   * Global Events type that includes all integration events and custom events.
   * Use this type to reference any event that can occur in the system.
   *
   * Events are namespaced by their source:
   * - Integration events: "<integration>:<eventName>" (e.g., "linear:issueCreated")
   * - Custom events: "<eventName>" (e.g., "orderPlaced", "userRegistered")
   */
  export type Events = {
    "webchat:conversationStarted": Integrations["webchat"]["events"]["conversationStarted"];
    "webchat:trigger": Integrations["webchat"]["events"]["trigger"];
    "chat:custom": Integrations["chat"]["events"]["custom"];
    register: {};
  };

  // Export helper type for event names
  export type EventName = keyof Events;

  // Export helper to get event payload type
  export type EventPayload<T extends EventName> = Events[T];
}
