////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Generated at: 2026-04-02T22:26:48.132Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/plugins" {
  export type Plugins = {};
}
