////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Generated at: 2026-04-02T22:26:48.136Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/tags" {
  /**
   * Bot-level tags defined in agent.config.ts
   */
  export type BotTags = Record<string, string | undefined>;

  /**
   * User-level tags defined in agent.config.ts
   */
  export type UserTags = Record<string, string | undefined>;

  /**
   * Conversation-level tags defined in agent.config.ts
   */
  export type ConversationTags = {
    /**
     * ADK Sync Timestamp
     *
     * Built-in: Last synced message timestamp. Automatically updated by the ADK when messages are processed.
     */
    adkSyncTs?: string | undefined;
  };

  /**
   * Message-level tags defined in agent.config.ts
   */
  export type MessageTags = Record<string, string | undefined>;

  /**
   * Workflow-level tags defined in agent.config.ts
   */
  export type WorkflowTags = Record<string, string | undefined>;
}
