////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Integration: chat
// Version: 0.7.7
// File: chat/actions.ts
// Hash: 59cd844e2cad0913f3cbab9bc848fac7f6374f234f657346376263ae82d52621
// Updated at: 2026-03-30T12:10:59.648Z
////////////////////////////////////////////////////////

export type Integration_Actions_Chat = {
  /**
   * Title: Send Custom Event
   * Description: Send a custom event from the bot to the chat client
   */
  sendEvent: {
    input: {
      /** The ID of the conversation to send the event to */
      conversationId: string;
      /** Custom data payload to send with the event */
      payload: { [key: string]: any };
    };
    output: {};
  };
};
