////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Integration: chat
// Version: 0.7.7
// File: chat/configurations.ts
// Hash: 59cd844e2cad0913f3cbab9bc848fac7f6374f234f657346376263ae82d52621
// Updated at: 2026-03-30T12:10:59.648Z
////////////////////////////////////////////////////////

export type Integration_Configurations_Chat = {
  /**
   * @title Default
   * Default configuration
   */
  default: {
    /** Only set this config if you plan on signing your user key yourself. Key used to sign and verify user keys; JWT tokens with HS256 algorithm. */
    encryptionKey?: string;
    /** Only set this config if you want to listen on a webhook instead of the standard SSE stream. URL where all incoming and outgoing messages / events are sent to. */
    webhookUrl?: string;
    /** Secret forwarded to the webhook URL. */
    webhookSecret?: string;
  };
};
