////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Integration: chat
// Version: 0.7.7
// File: chat/events.ts
// Hash: 59cd844e2cad0913f3cbab9bc848fac7f6374f234f657346376263ae82d52621
// Updated at: 2026-03-30T12:10:59.648Z
////////////////////////////////////////////////////////

export type Integration_Events_Chat = {
  /**
   * Title: Custom Event
   * Description: Custom event sent from the chat client to the bot
   */
  custom: {
    /** The ID of the user who sent the custom event */
    userId: string;
    /** The ID of the conversation where the event was sent */
    conversationId: string;
    /** Custom data payload sent with the event */
    payload: { [key: string]: any };
  };
};
