////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Integration: chat
// Version: 0.7.7
// File: chat/index.ts
// Hash: 59cd844e2cad0913f3cbab9bc848fac7f6374f234f657346376263ae82d52621
// Updated at: 2026-03-30T12:10:59.648Z
////////////////////////////////////////////////////////

import { Integration_Actions_Chat } from "./actions";
import { Integration_Channels_Chat } from "./channels";
import { Integration_Events_Chat } from "./events";
import { Integration_Users_Chat } from "./users";
import { Integration_Configurations_Chat } from "./configurations";

export * from "./actions";
export * from "./channels";
export * from "./events";
export * from "./users";
export * from "./configurations";

export type Integration_All_Chat = {
  actions: Integration_Actions_Chat;
  channels: Integration_Channels_Chat;
  events: Integration_Events_Chat;
  users: Integration_Users_Chat;
  configurations: Integration_Configurations_Chat;
};
