////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.17.0
// Integration: chat
// Version: 0.7.7
// File: chat/users.ts
// Hash: 59cd844e2cad0913f3cbab9bc848fac7f6374f234f657346376263ae82d52621
// Updated at: 2026-03-30T12:10:59.648Z
////////////////////////////////////////////////////////

export type Integration_Users_Chat = {
  tags: /**
     * Title: Foreign ID
     * Description: Copy of the foreign ID of the user
     */
    | "chat:fid" /**
       * Title: User Profile
       * Description: Custom profile data of the user encoded as a string
       */
    | "chat:profile";
};
